mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=zoo
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=zoo
    - MYSQL_PASSWORD=zoo
    - MYSQL_DATABASE=zoo
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"